### ISSUE TITLE
pls add android 10 as a requirement (wiki)

### ISSUE THREAD

**Issue by steadfasterX** [stevesoltys/seedvault#106]
1. https://github.com/stevesoltys/seedvault/pull/105
1. https://github.com/stevesoltys/seedvault/wiki/Building-with-AOSP (requirements topic)

after digging around with the aosp inline build I found that it simply does not work. thx to https://github.com/stevesoltys/seedvault/issues/97 I got the confirmation that android 10 is needed.
so I switched to prebuilt and now realized that ofc that will not work as well (hoped that the a10 req would be just related to building..):

`01-02 07:50:17.629  1070  1070 W PackageManager: Failed to parse /system/priv-app/Seedvault: /system/priv-app/Seedvault/Seedvault.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #28)`

it would have saved me a lot of time when the above 2 things would have been there.

btw any chance to get that running in PIE ever?

**Comment by grote** [comment]
We only support the latest Android version and explained somewhere else why. You can still use and maintain older versions. In the future we might branch out branches per AOSP version. An `android9` branch would have been branched out before 37ffacbafef83a0cdedc6347dcbd1049ff23f6a4 for example.

**Comment by steadfasterX** [comment]
yes. but that is not mentioned in the README and is not mentioned in the build guide. so it is missing IMHO in the most prominent places where a user would look first (instead of digging into commits etc)

**Comment by grote** [comment]
Yep help with documenting this is very much appreciated. Thanks!

**Comment by steadfasterX** [comment]
@grote what is the best way to get help getting it work in pie?
I have [reverted the android10](https://code.binbash.rocks:8443/Android/seedvault/commit/b199250b6d1f791b94723f948e153e9b1850fb03) commit and fixed build issues [here](https://code.binbash.rocks:8443/Android/seedvault/commit/de7c879c152efe504c423ba2722b5b161c6e5cc6)

but I need someone with more knowledge then me to verify that this was made correctly or completely stupid :P 
at least it builds now :)

**Comment by grote** [comment]
@steadfasterX maybe talk to @stevesoltys if he let's you maintain an `android9` branch.

As for making sure it works, I'd start with the instrumentation and unit tests followed by actual on-device testing.

**Comment by stevesoltys** [comment]
I'm okay with an Android 9 branch.

There won't be any prebuilt repo for it, but since this is now inline, that should be fine.

**Comment by steadfasterX** [comment]
closing that issue as #105 got merged and wiki is updated, thx!
