### ISSUE TITLE
Unable to take backup when replugging USB drive

### ISSUE THREAD

**Issue by mikeNG** [stevesoltys/seedvault#116]
When I plugged my USB drive off and plugged it back on, creating a new backup from "Backup now" option fails. I have to select the storage again in order for the backup to succeed, even if the exact same storage was selected before.

**Comment by grote** [comment]
Can you please get me a logcat of the replugging and trying to back up part until it fails?

**Comment by chirayudesai** [comment]
Also which devices was this on? sargo / 3a ?

**Comment by mikeNG** [comment]
This was on jasmine, I will get a logcat

**Comment by mikeNG** [comment]
Looks like I can no longer reproduce this with latest develop branch updates

**Comment by grote** [comment]
It might still be interesting to know if you see a device initialization in the log after plugging in the drive and triggering a backup.
