### ISSUE TITLE
Backup doesn't work on Android 11 based Graphene OS

### ISSUE THREAD

**Issue by jazzm0** [stevesoltys/seedvault#156]
When I choose backup, select usb/internal memory, the backup seems to finish, but neither in the internal storage nor on the external drive I can find any backup files. I used the graphene OS image https://github.com/GrapheneOS/platform_manifest/releases/tag/RP1A.201005.004.2020.10.23.04. https://releases.grapheneos.org/flame-factory-2020.10.23.04.zip. Also, when I change the backup storage the App backup status switches to Never.

**Comment by dznsm** [comment]
Works for me on latest stable GrapheneOS. Are you showing hidden files/folders when you are looking for the backup? 
You should find the `.SeedVaultAndroidBackup` directory in the location you set for the backup.

**Comment by jazzm0** [comment]
yupp, that's it, didn't expect a hidden directory.
