### ISSUE TITLE
Include BorgBackup via ssh

### ISSUE THREAD

**Issue by rugk** [stevesoltys/seedvault#45]
An awesome idea would maybe to include a way to use BorgBackup to backup all the data from your phone. See: https://github.com/borgbackup/borg/issues/1155

**Comment by grote** [comment]
borgbackup is expecting a file system to work on which we can not provide from an Android context. Also, it is written in Python which doesn't just run on Android. So I see very little chances for this request.

**Comment by rugk** [comment]
Well… with Termux it can already run on Android.

**Comment by stevesoltys** [comment]
If possible, this could also have potential compatibility issues across different versions of Android. I only skimmed that thread, but it seems like we may have to bundle a binary application, which doesn't sound like something we'd want for this application.

We want to maintain portability across different Android forks and the overhead required to test and maintain this is likely not worth it.

**Comment by stevesoltys** [comment]
For now I will close this, if there are any suggestions on how this could be done without the above issues we can consider re-opening it.
