### ISSUE TITLE
Improve UX for auto-restore when using removable storage

### ISSUE THREAD

**Issue by grote** [stevesoltys/seedvault#51]
Auto-restore restores app data when an app is re-installed and had a backup available. When backups are stored on removable storage (something not envisoned/supported by Google) the backup is not available to be restored. Though obvious to technical people, not all users might be aware of it.

So maybe we should explain this to users either once (when setting up removable storage) or every time an app is installed that we have a backup for on removable storage maybe with a heads up notification.

**Comment by chirayudesai** [comment]
A notification every time an app is installed might get annoying.
Having this noted while backing up and also as a "Note: ..." on the backup screen would be good.

Also relevant would be how auto-restore works when backing up to a cloud provider.
You're likely to be online when installing an apk so this should be fine.

**Comment by grote** [comment]
The idea was to show the notification only when an app gets installed that we had backed up already, not any new app. Usually, people don't re-install apps that often, but if they do, they might want their old app data back.

>  Having this noted while backing up and also as a "Note: ..." on the backup screen would be good.

Yeah this could be a warning in the preference summary of the Auto Restore settings.

**Comment by chirayudesai** [comment]
> The idea was to show the notification only when an app gets installed that we had backed up already, not any new app. Usually, people don't re-install apps that often, but if they do, they might want their old app data back.
> 
True, I guess that would be okay then.
> > Having this noted while backing up and also as a "Note: ..." on the backup screen would be good.
> 
> Yeah this could be a warning in the preference summary of the Auto Restore settings.

**Comment by grote** [comment]
> Yeah this could be a warning in the preference summary of the Auto Restore settings.

![device-2020-01-03-093210](https://user-images.githubusercontent.com/244947/71723591-fa796880-2e0b-11ea-916d-6286b5471aaf.png)

**Comment by grote** [comment]
![device-2020-01-03-122715](https://user-images.githubusercontent.com/244947/71733301-ffe4ac00-2e27-11ea-854a-c044cd0eef6e.png)![device-2020-01-03-122752](https://user-images.githubusercontent.com/244947/71733302-007d4280-2e28-11ea-9581-00457116091d.png)

**Comment by grote** [comment]
Has been implemented in #67.
