### ISSUE TITLE
Try to remove the requirement of signing the app with the platform key

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#58]
Currently, Seedvault needs to be signed with the platform key to work (the same key the OS is signed with). It could be possible to get rid of this requirement. For example, by providing an alternative UI path to select storage when the `MANAGE_DOCUMENTS` permission was not granted.

If that works, we can use a hidden-api-whitelist configuration instead of signing with platform cert to continue to access the hidden APIs we need for backup: 
https://github.com/LineageOS/android_vendor_lineage/commit/dab1569b810eb3e1185b1f6521fa159fce57095d example whitelist file

Tasks:

* [x] detect at runtime if permission was granted and choose backup/restore storage UI path accordingly
* [x] implement different UI storage choosing path for backup
* [x] implement different UI storage choosing path for restore
  * [x] ensure the user can re-choose a storage location if no backups are found at chosen location
  * [ ] give option to install NextCloud (if needed)

**Comment by chirayudesai** [comment]
Needs to betested to be sure that we don't need platform cert for anything else.

@stevesoltys @grote can you think of anything else needing this apart from accessing private APIs?

**Comment by grote** [comment]
No, I guess we need to test it.

@stevesoltys this is interesting, because it would allow users of other ROMs such as LineageOS to flash SeedVault like they flash gapps without the need to have the app blessed by the ROM.

**Comment by chirayudesai** [comment]
Unfortunately this won't work.

Permission MANAGE_DOCUMENTS is "signature|documentor", so that needs platform cert.

**Comment by grote** [comment]
If this is ever desired, we could think about a fallback mode that checks if `MANAGE_DOCUMENTS` is granted and if not falls back to the user to pick a storage location for the app to use. Worse UX, but doable.

**Comment by chirayudesai** [comment]
Yes. However, it should also be noted that I did not test any further since just trying to use the `MANAGE_DOCUMENTS` permission causes a crash.

So one should try to check other functionality if possible before going through the effort of implementing that fallback.

**Comment by grote** [comment]
> we could test with the publicly available R betas and see if it works.

@chirayudesai maybe just for this issue, we should test with Android 10 first, because the 11 betas might break other things we don't know about, yet.

**Comment by chirayudesai** [comment]
For sure. Do you know offhand what needs to be stubbed out for not `MANAGE_DOCUMENTS` to work?

**Comment by grote** [comment]
I made a first attempt at https://github.com/grote/backup/tree/no-platform-key please let me know if this still crashes due to access to `MANAGE_DOCUMENTS`.

**Comment by chirayudesai** [comment]
Backup works, restore doesn't
> E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3AAndroid/document/primary%3AAndroid from pid=5544, uid=10053 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

Had to add it to hidden-api-whitelist, see: https://github.com/chirayudesai/backup/commit/c372d40ad883ab1bef251e73428ecb0d22266f1a

**Comment by chirayudesai** [comment]
If there's any other AOSP / stock system apps that also use File Chooser, we can see what they do / if they have any other workaround this, apart from `requestlegacystorage`

**Comment by grote** [comment]
Thanks for testing! I'd say this validates our theory and indicates that this can be done.

Should we then also re-open #9?

> If there's any other AOSP / stock system apps that also use File Chooser, we can see what they do / if they have any other workaround this, apart from requestlegacystorage

Not sure I understand. The workaround in my branch uses an intent to let the user pick an arbitrary storage location. This should continue to work with R and without legacy storage.

**Comment by chirayudesai** [comment]
> Thanks for testing! I'd say this validates our theory and indicates that this can be done.
Agreed. We might want to stick with platform key as the default for better UX though.
> 
> Should we then also re-open #9?
Done
> 
> > If there's any other AOSP / stock system apps that also use File Chooser, we can see what they do / if they have any other workaround this, apart from requestlegacystorage
> 
> Not sure I understand. The workaround in my branch uses an intent to let the user pick an arbitrary storage location. This should continue to work with R and without legacy storage.

Ah I meant if any app also works around not having MANAGE_DOCUMENTS, given that the only user of `MANAGE_DOCUMENTS` that I see in AOSP is DocumentsUI itself. See https://cs.android.com/search?q=MANAGE_DOCUMENTS%20file:AndroidManifest.xml

Anyway, the intent picker is still a good alternative anyway.

**Comment by grote** [comment]
The only thing missing here is "give option to install NextCloud (if needed)", but I am not sure we need to provide that. If an OEM wants to use Seedvault without that permission, they can take care of providing the storage providers that they white-list.

**Comment by rugk** [comment]
Given this is then fixed, what about https://github.com/stevesoltys/seedvault/issues/8 again? I know, I read https://github.com/stevesoltys/seedvault/issues/8#issuecomment-688932187, so maybe we cannot put it into F-Droid? But really, why not like the F-Droid OTA ZIP? After all, just state there it needs to be flashed.

I just want to propose a good distribution way then. Alternatively maybe just attach OTA ZIPs [to the releases](https://github.com/stevesoltys/seedvault/releases) and include some installation instructions in the Readme… :thinking:

**Comment by grote** [comment]
Isn't what you are talking about #9 ?

**Comment by rugk** [comment]
Ah yes, indeed, thanks! :smiley:
