### ISSUE TITLE
Better progress bar

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#59]
I feel like we can have a better progress bar, it would be good for UX as well.

Some things
1) For the user, knowing full backup progress is better if possible. Per-app progress isn't really too helpful tbh.
I understand that this may involve some sort of global progress tracking given that right now from what I'm told the OS does not report when a particular backup invocation is done.

2) Seeing random system apps with their package names as Not backed up, maybe we should skip those?

3) Some apps fail backup, I noticed Maps mailing for example, but that went away in the blink of an eye so I was lucky to see it. Somewhat related to #19
i.e, I wouldn't know that this app failed without having per-app status shown in the app and seeing that it isn't backed up / last backup date doesn't match.
Also, I have two apps named "Maps" to make it worse, couldn't tell which one failed, the app would show icon which would help.

**Comment by chirayudesai** [comment]
Also, to note that stock does show a proper full progress status bar that just says "Backing up your data" when you manually trigger a backup.

**Comment by chirayudesai** [comment]
2) wouldn't be an issue once 1) is implemented, so that could be skipped entirely I guess.

**Comment by grote** [comment]
Implemented in https://github.com/grote/backup/commit/6ed522bfb7d04d7d1f886a2ba3b61796128545ad and merged to `develop` already.
