### ISSUE TITLE
Show something when an explicitly triggered backup is finished

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#61]
When a backup is triggered explicity using the menu item "Backup Now", it shows the normal progress bar, and then nothing at all.

It would be good to have a "backup complete" notification in this case.

Otherwise, even something in the app itself showing the status of the last backup would be good too.

Basically, it would be good to not have the notification just disappear like that without anything else.

**Comment by grote** [comment]
> even something in the app itself showing the status of the last backup would be good too.

This should probably be a dedicated ticket for showing a list of apps and their backup status.

**Comment by chirayudesai** [comment]
> > even something in the app itself showing the status of the last backup would be good too.
> 
> This should probably be a dedicated ticket for showing a list of apps and their backup status.

#19 is related.

**Comment by chirayudesai** [comment]
Another thing to add to this, semi-related.

The notification could also be shown when an implicit backup is finished.

Tapping it would lead to the list of apps with their backup status.

For explicit backup the notification would be shown always.
For implicit backups it could be shown only on failure or when an app was missed, so that the user knows.

**Comment by grote** [comment]
> The notification could also be shown when an implicit backup is finished.

If you let me know how to detect that an  implicit backup is finished, I'll look into it ;)

**Comment by chirayudesai** [comment]
Notification for explicit backup impelemented, could keep this open for the implicit background backups.

Both of those should open the list #69 onClick.

**Comment by grote** [comment]
As this is implemented already in #67 already, setting the notification target should be part of #69 really, maybe as part of a task list.

**Comment by grote** [comment]
Can be closed.
