### ISSUE TITLE
Backup on-device contacts

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#66]
We should also backup Contacts that are only stored on-device aka those that are not synced via a CardDAV or other sync solution.

**Comment by chirayudesai** [comment]
https://github.com/jberkel/sms-backup-plus FOSS app that backs up SMS and call logs.

As for contacts, the app itself can export a VCF file via Contacts -> Settings -> Export

**Comment by grote** [comment]
Apache licensed is good already, so we could copy over code fragments or ideally entire packages if data retrieval is sufficiently encapsulated. Haven't looked at any of the code, yet.

**Comment by grote** [comment]
So I checked this and it seems that SMS already get backed up and restored. Further confirmations for that are welcome.

To get only on-device contacts, we can do a query for `ContactsContract.Data.CONTENT_URI` where `ContactsContract.SyncState.ACCOUNT_TYPE` is `null`. Get their `ContactsContract.Data.LOOKUP_KEY` (filter out duplicates) and then use [`Contacts.CONTENT_MULTI_VCARD_URI`](https://developer.android.com/reference/android/provider/ContactsContract.Contacts#CONTENT_MULTI_VCARD_URI) to get an URI to vCard with all those contacts in it.
For restore, we can ideally push this vcard back somehow without needing to parse it. But I haven't checked that part.

**Comment by chirayudesai** [comment]
Can confirm SMSes do get restored.

**Comment by khimaros** [comment]
Is any action required to include this in an AOSP build beyond including the SeedVault module?

**Comment by grote** [comment]
If you use the provided `Android.bp` file to build it, the contacts backup gets pulled in automatically: https://github.com/stevesoltys/seedvault/blob/0272a094ec8bc86286bc108457f852122e2f558e/Android.bp#L44-L48

Feedback on how all of this works is very welcome, btw.!
