### ISSUE TITLE
Google Maps does not get backed up at all

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#68]
1. Data backup fails, it can't find it's backup agent, no gapps, but I do have microG
2. APK isn't backed up at all either

Backup Log:

> 01-17 15:37:25.265 +0000  1368 20720 D KeyValueBackupTask: Starting key-value backup of com.google.android.apps.maps
> 01-17 15:37:25.267 +0000  1368 20720 D BackupManagerService: awaiting agent for ApplicationInfo{fd1299 com.google.android.apps.maps}
> 01-17 15:37:25.292 +0000   892   892 D Zygote  : Forked child process 22972
> 01-17 15:37:25.295 +0000  1368  1426 I ActivityManager: Start proc 22972:com.google.android.apps.maps/u0a115 for backup {com.google.android.apps.maps/com.google.android.apps.gmm.backup.GmmPersistentBackupAgentHelper}
> 01-17 15:37:25.306 +0000 22972 22972 E droid.apps.map: Not starting debugger since process cannot load the jdwp agent.
> 01-17 15:37:25.348 +0000 22972 22972 I droid.apps.map: The ClassLoaderContext is a special shared library.
> 01-17 15:37:25.372 +0000  2932  2932 D ParseCancel: by not found
> 01-17 15:37:25.374 +0000  6632  6632 I nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Ignore notification
> 01-17 15:37:25.376 +0000  1687  1687 D InterruptionStateProvider: No pulsing: not important enough: 0|com.stevesoltys.seedvault|1|null|10049
> 01-17 15:37:25.378 +0000  1687  1687 D InterruptionStateProvider: No pulsing: not important enough: 0|com.stevesoltys.seedvault|1|null|10049
> 01-17 15:37:25.495 +0000 22972 22972 W droid.apps.map: JIT profile information will not be recorded: profile file does not exits.
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : QUALCOMM build                   : 4a00b69, I4e7e888065
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : Build Date                       : 04/09/19
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : OpenGL ES Shader Compiler Version: EV031.26.06.00
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : Local Branch                     : mybranche95a5ea3-cf05-f19a-a0e7-5cb90179c3d8
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : Remote Branch                    : quic/gfx-adreno.lnx.1.0
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : Remote Branch                    : NONE
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : Reconstruct Branch               : NOTHING
> 01-17 15:37:25.706 +0000 22972 22998 I Adreno  : Build Config                     : S P 8.0.6 AArch64
> 01-17 15:37:25.724 +0000  1368  6785 D BackupManagerService: agentConnected pkg=com.google.android.apps.maps agent=android.os.BinderProxy@faac13f
> 01-17 15:37:25.724 +0000  1368 20720 I BackupManagerService: got agent android.app.IBackupAgent$Stub$Proxy@84faa0c
> 01-17 15:37:25.724 +0000  1368 20720 D KeyValueBackupTask: Invoking agent on com.google.android.apps.maps
> 01-17 15:37:25.726 +0000 20616 22212 I BackupCoordinator: Get backup quota for com.google.android.apps.maps. Is full backup: false.
> 01-17 15:37:25.726 +0000 20616 22212 I BackupCoordinator: Reported quota of 10485760 bytes.
> 01-17 15:37:25.727 +0000  1368 20720 V BackupAgentTimeout: getKvBackupAgentTimeoutMillis(): 30000
> 01-17 15:37:25.732 +0000 22972 22998 I Adreno  : PFP: 0x016ee183, ME: 0x00000000
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: onBackup (com.google.android.apps.gmm.backup.GmmPersistentBackupAgentHelper) threw
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: java.lang.NullPointerException: throw with null exception
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at bulf.a(PG:20)
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at com.google.android.apps.gmm.backup.GmmPersistentBackupAgentHelper.a(PG:3)
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at bkhc.onBackup(PG:7)
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at com.google.android.apps.gmm.backup.GmmPersistentBackupAgentHelper.onBackup(PG:12)
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at android.app.backup.BackupAgent$BackupServiceBinder.doBackup(BackupAgent.java:987)
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at android.app.IBackupAgent$Stub.onTransact(IBackupAgent.java:294)
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
> 01-17 15:37:25.735 +0000 22972 22990 D BackupServiceBinder: 	at android.os.Binder.execTransact(Binder.java:994)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : Caught a RuntimeException from the binder stub implementation.
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : java.lang.NullPointerException: throw with null exception
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at bulf.a(PG:20)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at com.google.android.apps.gmm.backup.GmmPersistentBackupAgentHelper.a(PG:3)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at bkhc.onBackup(PG:7)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at com.google.android.apps.gmm.backup.GmmPersistentBackupAgentHelper.onBackup(PG:12)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at android.app.backup.BackupAgent$BackupServiceBinder.doBackup(BackupAgent.java:987)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at android.app.IBackupAgent$Stub.onTransact(IBackupAgent.java:294)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
> 01-17 15:37:25.738 +0000 22972 22990 W Binder  : 	at android.os.Binder.execTransact(Binder.java:994)
> 01-17 15:37:25.738 +0000  1368 20720 W KeyValueBackupTask: Agent com.google.android.apps.maps error in onBackup()
> 01-17 15:37:25.738 +0000 20616 22212 I NotificationBackupObserver: Completed. Target: com.google.android.apps.maps, status: -1003

**Comment by chirayudesai** [comment]
From the log I can understand why it's data didn't get backed up.

However, I feel that the APK should've gotten backed up either way.

It's the only app missing on my device after restoring a backup taken from my main phone.

**Comment by grote** [comment]
So the problem here seems to be that an exception is thrown and thus `BackupTransport#performBackup()` is never called.

Two possible solutions:
1. Try to back up the APK at an earlier stage before the exception is thrown
2. Somehow add apps that failed like this to the special backup run of non-allows app APKs

**Comment by chirayudesai** [comment]
This is a very pecuilar edge case, at this point I'm mainly curious to see if it's hit by many other apps at all.

However, when we do want to solve this I would prerfer going for the second option, sounds more reliable.

**Comment by grote** [comment]
Please feel free to add more apps to this ticket if there are cases. Maybe the title should be more generic then as well?

**Comment by grote** [comment]
Similar issue without exception:

```ruby
2020-01-18 14:47:01.235 D/KeyValueBackupTask: Starting key-value backup of com.whatsapp
2020-01-18 14:47:01.238 D/BackupManagerService: awaiting agent for ApplicationInfo{a538e95 com.whatsapp}
2020-01-18 14:47:01.241 D/BackupManagerService: agentConnected pkg=com.whatsapp agent=android.os.BinderProxy@f84c2c1
2020-01-18 14:47:01.242 I/BackupManagerService: got agent android.app.IBackupAgent$Stub$Proxy@123ea66
2020-01-18 14:47:01.242 D/KeyValueBackupTask: Invoking agent on com.whatsapp
2020-01-18 14:47:01.244 I/BackupCoordinator: Get backup quota for com.whatsapp. Is full backup: false.
2020-01-18 14:47:01.244 I/BackupCoordinator: Reported quota of 10485760 bytes.
2020-01-18 14:47:01.245 V/BackupAgentTimeout: getKvBackupAgentTimeoutMillis(): 30000
2020-01-18 14:47:01.247 D/BackupHelperDispatcher: handling new helper 'backup_helper_key'
2020-01-18 14:47:01.250 I/BackupRestoreController: Getting widget state for user: 0
2020-01-18 14:47:01.250 V/BackupManagerConstants: getBackupFinishedNotificationReceivers(...) returns 
2020-01-18 14:47:01.251 I/NotificationBackupObserver: Completed. Target: com.whatsapp, status: 0
```

**Comment by grote** [comment]
Can probably be closed if the issue can not be reproduced anymore.

**Comment by chirayudesai** [comment]
This can still be reproduced with Google Maps.

**Comment by grote** [comment]
Note that I consider this ticket to be about the Google Maps APK not getting backed up. I don't think the crash inside the GmmPersistentBackupAgentHelper is our fault. They might be expecting a google backup or something.
