### ISSUE TITLE
Show status of backed up apps individually

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#69]
It would be good to have an app list like the one that's shown during restore, with the status of each individual app.

It could show if they're backed up, when they got backed up last, and if they aren't backed up - the reason for that.

**Comment by chirayudesai** [comment]
This used to be a thing on stock, but not anymore.

See: https://youtu.be/NforgNfwsnw

![image](https://user-images.githubusercontent.com/952062/72631257-0facd600-397a-11ea-8db4-ddebdb846f38.png)

**Comment by grote** [comment]
As #71 was merged, this can be closed.
