### ISSUE TITLE
Allow choosing apps to be backed up

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#70]
Sometimes we may not want to backup certain apps.

A whitelist with all apps selected by default would work well.

This could somehow be integrated into #69 as well, to directly allow editing that list after entering edit mode by pressing a button on the top or a floating button or something like that.

It could also allow skipping just APK or data backups for some apps.

Showing the backup size, and allowing to sort by size could be beneficial here.

**Comment by chirayudesai** [comment]
Related / almost the same? #19 

Also, note that while this can get complicated real quick, a good starting point could be to just allow completely skipping an app for backup once we have the list #69  implemented.

Fine grained tuning could come later.

**Comment by grote** [comment]
> This could somehow be integrated into #69 as well, to directly allow editing that list after entering edit mode by pressing a button on the top or a floating button or something like that.

Great idea!

> Showing the backup size, and allowing to sort by size could be beneficial here.

I'd like to have this as a dedicated ticket to be done in a later iteration as it is not strictly part of the core feature, but a nice-to-have add-on.

**Comment by stevesoltys** [comment]
Closed via https://github.com/stevesoltys/seedvault/pull/72/commits/324da2a9e91b9a96323ca4de1a7debd2131e434a.
