### ISSUE TITLE
Trying to build with MicroG

### ISSUE THREAD

**Issue by tobiasKaminsky** [stevesoltys/seedvault#79]
Hi,

thanks for the amazing app (and Nextcloud support)!
I now want to build this via microG, following https://github.com/stevesoltys/seedvault/wiki/Building-with-AOSP

But step 4 is not clear to me: 
what is the current backup application I should replace?

Thanks :-)

**Comment by tobiasKaminsky** [comment]
I only find 
```
  <project path="external/libbackup" name="platform/external/libbackup" groups="pdk" remote="aosp" />
```

**Comment by grote** [comment]
I didn't write the instructions, but if there's no current backup application, I think you can just add this line instead of replacing another one.

**Comment by stevesoltys** [comment]
Sorry, I've updated the instructions. You don't need to replace anything.

**Comment by grote** [comment]
Is the `oreo-r3-release` branch in the instructions correct given that the latest version requires Android 10?

**Comment by stevesoltys** [comment]
I changed it to `master`.

**Comment by tobiasKaminsky** [comment]
> Sorry, I've updated the instructions.

There is no need  to be sorry.
Thanks for the amazing job!
I will give it a try soon :-)

**Comment by tobiasKaminsky** [comment]
I think this is somehow related, as I am not sure if my building was successful:
I can see seedvault as an hidden app ver 1.0.0 but now I have no idea how to backup.
The backup mechanism still mentions google server only.

**Comment by grote** [comment]
You might need to enable the backup transport: https://github.com/stevesoltys/seedvault/issues/80
