### ISSUE TITLE
cannot enable backups through settings with seedvault-prebuilts 1.0.0

### ISSUE THREAD

**Issue by khimaros** [stevesoltys/seedvault#80]
After including seedvault-prebuilts in my RattlesnakeOS image, Settings > System > Backups remains "Off" and selecting it shows an empty list.

This may only be an issue when building seedvault into a later OTA after already performing initial device setup where seedvault was absent.

The workaround that fixed this for me was:

```
$ adb shell bmgr enable true
$ adb shell bmgr transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport
```

At least, it would be helpful to document this workaround, which I found in https://github.com/stevesoltys/seedvault/pull/48

Thanks for building this excellent piece of software!

**Comment by stevesoltys** [comment]
Thanks! I updated the documentation to include a permanent solution to this (from @grote and @chirayudesai [here](https://github.com/stevesoltys/seedvault/pull/48#issuecomment-562587957)).

Let me know if you think it suffices now.

**Comment by khimaros** [comment]
If you are referring to the documentation at https://github.com/stevesoltys/seedvault/wiki/Building-with-AOSP -- it is definitely an improvement! I might also recommend documenting the `adb shell` workaround for folks who have already deployed an image and want a single-device fix. As far as I can tell, doing this once is sufficient and seems to be preserved across future OTA updates.

**Comment by stevesoltys** [comment]
Good idea. I've added that as a note at the end.
