### ISSUE TITLE
Seafile storage?

### ISSUE THREAD

**Issue by cyrinux** [stevesoltys/seedvault#84]
Hi,
Thanks for this cool stuff.

I dont use nextcloud but my seafile instance.

How can I use seafile for my backup? 
I use it from GrapheneOS, maybe this change something?
Or is it an API problem, like nextcloud expose something that seafile doesn't ?

Tell me if I can help, providing some info. I would be very happy to be able to store in my seafile.

Regards

**Comment by dznsm** [comment]
Hey @cyrinux,
Think Seafile will need to add support. Heres the related issue that shows how Nextcloud integration was made possible https://github.com/stevesoltys/seedvault/issues/12

**Comment by grote** [comment]
@dznsm is correct. However, once supported, Seafile needs to be white-listed be the OEM shipping Seedvault: https://github.com/stevesoltys/seedvault/blob/88a250ff5c46c2cf28e603a262713cf45eba438f/app/src/main/res/values/config.xml#L13-L17

**Comment by cyrinux** [comment]
Thanks guy, I so opened an issue in seafile-server with cross linking.

**Comment by grote** [comment]
Seafile needs to add support for Android's Storage Access Framework (DocumentsProvider with open file tree) to their app. This is unrelated to their server and even unrelated to Seedvault which just uses that standard framework.

**Comment by cyrinux** [comment]
Ok I see 👍   I correct this !

**Comment by michaelulmer** [comment]
I also use seafile. 
I'm trying to figure out what this projects does in general. I dont unterstand it yet. could someone please explain

**Comment by cyrinux** [comment]
@michaelulmer this project is a opensource android backup solution, build for example in the ungoogled android grapheneOS project.

**Comment by stevesoltys** [comment]
Closing this for now since there is no work necessary on our end.

**Comment by grote** [comment]
So since this seems to be supported in Seafile, an OEM wanting to support that, would need to white-list Seafile for Seedvault (after some testing of course).

**Comment by MajorP93** [comment]
@grote there seem to be additional steps / implementation in the source code needed.

I have added <item>com.seafile.seadroid2</item> to "storage_authority_whitelist" array in app/src/main/res/values/config.xml and recompiled LineageOS 18.1.

The seafile app (com.seafile.seadroid2) is installed and set up (connection to server).

Seafile is still not being shown in the Seedvault storage provider list.

It would be awesome if you could investigate this since Seafile is FOSS software and would fit perfectly as storage provider for seedvault.

**Comment by grote** [comment]
@MajorP93 please provide logcat output that happens when listing providers? Does Seafile storage show up in files app?

**Comment by MajorP93** [comment]
@grote checking the logcat during that event revealed the problem: com.seafile.seadroid2.documents has to be whitelisted instead of com.seafile.seadroid2.

Can the whitelist be edited directly on the phone or do I have to recompile?

Thanks for pushing me into the right direction!

If it turns out working I will create a PR at LineageOS.

**Comment by MajorP93** [comment]
@grote I recompiled the app after changing the whitelist entry and re-installed it using adb afterwards.

Works as expected!

Thanks alot!

Will create a PR at LineageOS now.

**Comment by MajorP93** [comment]
@grote I recompiled the app after fixing the whitelisting. I then pushed the new .apk file using adb.
The installation worked and now I am able to see and select Seafile as a storage provider.
Strangely it was just plain selecting, no asking for destination folder on the target or similar.

I then started a backup run. Seedvault get's stuck at 0% and nothing happens. On the Seafile target server there are no files arriving.

Maybe it is an idea to implement a generic WebDAV backend?
This would enable us to use any cloud solution that offers WebDAV.

Looking forward to a short reply.
Thanks in advance!

**Comment by grote** [comment]
> If it turns out working I will create a PR at LineageOS.

Remember that providers need to be whitelisted by the ROM, so they can ensure that the provider will be available during restore. Otherwise, backups can't be accessed.

> I then started a backup run. Seedvault get's stuck at 0% and nothing happens. On the Seafile target server there are no files arriving.

You need to check the logs again to found out what's going on.

> Maybe it is an idea to implement a generic WebDAV backend?

Yes, that would work a lot better than going through SAF.

**Comment by MajorP93** [comment]
Thanks for your reply!
> 
> You need to check the logs again to found out what's going on.
> 

I found a workaround, I had to create a library called ".SeedVaultAndroidBackup" on the target server (Seafile is organized in so-called libraries).
After doing so the backup worked without any issues!

**Comment by chirayudesai** [comment]
> After doing so the backup worked without any issues!

This is great! If you don't mind, could you try a restore as well?

Then we can add it as a supported provider here directly. :D
