### ISSUE TITLE
Apps using app bundles crash after getting restored

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#91]
Some apps do get installed on a restore, but they crash immediately when you try to launch them.

Need to uninstall and reinstall to get them working.

I've seen this with Twitter, and then some other app prompted me to something about needing Google Play to get the needed updates. This was also faced by somebody on #CalyxOS:matrix.org

I think this could be related to split APKs, need to check.

I do have a backup that can reproduce this, will get logs.

**Comment by chirayudesai** [comment]
Two apps with which I can reproduce this crash:
* com.google.android.apps.photosgo (Gallery Go)
* com.twiiter.android

Procedure:
* Install the above apps
* Make a backup with them, then restore
* Try launching the apps

Both have crashes related to resources

Twitter:
> 07-09 02:03:32.276  7771  7771 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.twitter.app.TwitterApplication: java.lang.IllegalStateException: Missing resources for the current device configuration.
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Missing resources for the current device configuration.
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at ol3.d(Twttr:4)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at ol3.onCreate(Twttr:5)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at mp3.onCreate(Twttr:11)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at com.twitter.app.TwitterApplication.onCreate(Twttr:6)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
07-09 02:03:32.276  7771  7771 E AndroidRuntime: 	... 8 more

Gallery Go:
> 07-09 02:03:29.190  7727  7727 E AndroidRuntime: android.view.InflateException: Binary XML file line #28 in com.google.android.apps.photosgo:layout/home_fragment: Binary XML file line #28 in com.google.android.apps.photosgo:layout/home_fragment: Error inflating class ImageView
07-09 02:03:29.190  7727  7727 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #28 in com.google.android.apps.photosgo:layout/home_fragment: Error inflating class ImageView
07-09 02:03:29.190  7727  7727 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080107
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.content.res.Resources.getValue(Resources.java:1351)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at xi.a(PG:24)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at xi.a(PG:18)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at oy.b(PG:5)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at sj.a(PG:10)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at sk.<init>(PG:8)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at sk.<init>(PG:2)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at of.a(PG:170)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at of.onCreateView(PG:388)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:242)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at czu.b(PG:20)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at dv.a(PG:88)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at fa.f(PG:73)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at et.a(PG:426)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at et.c(PG:415)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at et.d(PG:374)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at et.a(PG:406)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at dh.b(PG:98)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at et.b(PG:292)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at et.b(PG:508)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at et.b(PG:241)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at dh.a(PG:19)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at com.google.android.apps.photosgo.fragmentnavigator.FragmentNavigatorImpl.a(PG:63)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.arch.lifecycle.FullLifecycleObserverAdapter.a(PG:7)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at l.a(PG:4)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at i.b(PG:58)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at i.a(PG:31)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at i.a(PG:29)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at huw.a(PG:9)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at abr.a(PG:7)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at abq.onActivityPostStarted(PG:3)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1253)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7888)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-09 02:03:29.190  7727  7727 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by chirayudesai** [comment]
Full log:
[restore-apks-crash.log](https://github.com/stevesoltys/seedvault/files/4896872/restore-apks-crash.log)

**Comment by chirayudesai** [comment]
They're both using bundles, can see at:
* https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-8-51-0-release-00-release/
* https://www.apkmirror.com/apk/google-inc/gallery-go-by-google-photos/gallery-go-by-google-photos-1-1-9-318752680-release-release/

Not the exact versions I have/had, but recent enough. I installed them through Aurora Store on my device

**Comment by grote** [comment]
Thanks for the info! Could you please try if using auto-restore also triggers the issue? Install app, use quickly to create some data, backup, uninstall app, re-install app, start app.

**Comment by grote** [comment]
> `AndroidRuntime: java.lang.RuntimeException: Unable to create application com.twitter.app.TwitterApplication: java.lang.IllegalStateException: Missing resources for the current device configuration.`

My current hypothesis is that we only backup/restore the base APK, but not additional required device-specific app bundle files (maybe also dynamic feature modules?). So we'd need to figure out how to get those and how to deal with the possibility that a **backup gets restored on a device that needs a different app bundle**. The latter is probably the most tricky problem.

**Comment by chirayudesai** [comment]
For the latter the only solution I can think of is installing it from the store, and letting auto restore do it's work.
1) Show market/play/aurora links to those apks for convenience, and ask the user to install the apk manually for now. Much better than a crashing app, and do it while you're restoring the backup rather than finding out later when you try to use the app. They already have to uninstall and reinstall to fix the crash anyway.
2) We can then later on come back to that aurora integration, asking it to install apps automatically, but that would be long term, and an entirely separate discussion.

So then this boils down to whether we can detect compatibility reliably, and backup/restore said compatible apps without issue. That might cover a lot of the current use cases.

**Comment by grote** [comment]
Yeah that's probably the easiest and only solution we have available. However, it introduces the issue that an internet connection and the appropriate app store need to be available at the time of restore for this to work.

A more elaborate solution could combine your proposal with an app bundle compatibility detector that just restores the app bundle when no incompatibilities are found.

**Comment by chirayudesai** [comment]
Current:
* Apps with bundles gets restored but are broken and crash after install.

My proposal

v1:
* Skip those, and instead put in a play/aurora link for those (perhaps based on installerPackagename for both skipping it and the link) - Ask users to manually restore app while backup is available to have auto-restore than restore data.

v2:
* Start detecting compatible bundles, back them up, and restore them. Some might still be incompatible, for those we can still fallback to v1

v3:
* Automatically have aurora install the app in question, and then make sure the data gets restored.

v1 and v2 can be done at the same time depending on how long it takes. v1 should be fast, v2 unknown.
v3 would be future goals.

**Comment by grote** [comment]
So it seems that when `packageManager.getPackageInfo("com.twitter.android", 0).splitNames` is not `null`, but a list of configuration names, the app was installed as a bundle.

Still, I know too little about app bundles, but it might be possible to store the list of splits before install, compare it against what the device requires.

In the case of Twitter, in addition to the base APK, there's three split APKs:

* `/data/app/com.twitter.android-0LVngnq6MQ_xOhFXRsuDbQ==/split_config.arm64_v8a.apk`
* `/data/app/com.twitter.android-0LVngnq6MQ_xOhFXRsuDbQ==/split_config.en.apk`
* `/data/app/com.twitter.android-0LVngnq6MQ_xOhFXRsuDbQ==/split_config.xxxhdpi.apk`

Not sure if we could back those up as well and then restore them somehow, but I imagine that it is possible.

Except the architecture split, I guess the world wouldn't end if we just restored the language and resolution split as is without matching it to the device config. Certainly not ideal, but maybe better than falling back to manual install (especially when more and more apps will be bundles)?

**Comment by chirayudesai** [comment]
> So it seems that when `packageManager.getPackageInfo("com.twitter.android", 0).splitNames` is not `null`, but a list of configuration names, the app was installed as a bundle.
> 
> Still, I know too little about app bundles, but it might be possible to store the list of splits before install, compare it against what the device requires.
> 
> In the case of Twitter, in addition to the base APK, there's three split APKs:
> 
> * `/data/app/com.twitter.android-0LVngnq6MQ_xOhFXRsuDbQ==/split_config.arm64_v8a.apk`
> * `/data/app/com.twitter.android-0LVngnq6MQ_xOhFXRsuDbQ==/split_config.en.apk`
> * `/data/app/com.twitter.android-0LVngnq6MQ_xOhFXRsuDbQ==/split_config.xxxhdpi.apk`
> 

Do you know if the names of these splits standardised? Or rather are there any APIs to get names separately - i.e. arm64_v8a = arch, en = lang, xxxhdpi = density. We know that, but does the system know?

> Not sure if we could back those up as well and then restore them somehow, but I imagine that it is possible.
> 
> Except the architecture split, I guess the world wouldn't end if we just restored the language and resolution split as is without matching it to the device config. Certainly not ideal, but maybe better than falling back to manual install (especially when more and more apps will be bundles)?

Agree. Two things to consider, what would be more common:
1) Restoring a backup on the same device, or
2) Switching devices.

If one is a lot more common then the other we can optimise for that accordingly straight away.

Another thing is that anything we end up doing should not cause broken apps (i.e. current behvaiour), as it's not always obvious that it has to be re-installed. So:
1) Same device, so same splits should work, would be able to just install - easiest
2) Different device, all splits might not work, but like you said, resolution / language might not be end of the world.

Perhaps what we can do is try to install the splits for 2, but if any split fails just uninstall the app to avoid having a broken app. It'll be more complicated, but I think that would be better UX. And even better if we can figure this out programatically without actually having to install (something like hey is this split compatible?)

Also see https://developer.android.com/guide/app-bundle#known_issues , and TODO Revisit after 11.

**Comment by grote** [comment]
> Do you know if the names of these splits standardised?

Only thing I've found so far is the bundletool source code:

* density: [ResourcesUtils.java](https://github.com/google/bundletool/blob/24df0e8b56580cef68ba904b3a80e881f4fc641a/src/main/java/com/android/tools/build/bundletool/model/utils/ResourcesUtils.java#L61-L69)
* ABI: [AbiName.java](https://github.com/google/bundletool/blob/3586f8630e08733503ddbd1e74e10d4fb50e0d69/src/main/java/com/android/tools/build/bundletool/model/AbiName.java#L36-L42)

They seem to match the standard names for these things, like in the android app resource folders. Don't know if there's an official documentation with all of those in one place.

> Or rather are there any APIs to get names separately

`PackageInfo#splitNames` returns just the names in the same order as split APKs. For the Twitter app:

    [config.arm64_v8a, config.en, config.xxxhdpi]

As for installing, it seems like we just need to [install the split APKs like the base APK](https://github.com/nkalra0123/splitapkinstall/blob/bdfc8a3d794b68f157b8fd53b0240e15e0278e75/app/src/main/java/com/faith/apkinstaller/MainActivity.java#L321-L324). I haven't tried this out yet, though.

> if any split fails just uninstall the app to avoid having a broken app

Yeah that could work. We need to see though if the system rejects non-matching splits. As it isn't even checking required splits at all, it might just not care.

**Comment by chirayudesai** [comment]
> Yeah that could work. We need to see though if the system rejects non-matching splits. As it isn't even checking required splits at all, it might just not care.

Ok, if that is the case then we need to find some other way to figure out if an app would be broken and proceed accordingly. It can be the obvious stuff (matching splits, all installed, etc) - and hopefully that means it all works for the most part

**Comment by grote** [comment]
> Do you know if the names of these splits standardised?

So I checked some apps from [Google's success app bundle stories](https://developer.android.com/platform/technology/app-bundle). As it turns out the split names are rather custom:

```
in.redbus.android: [busHire, busHire.config.xxxhdpi, busPass, busPass.config.xxxhdpi, config.arm64_v8a, config.xxxhdpi, greenride, greenride.config.xxxhdpi]
com.airbnb.android: [config.arm64_v8a, config.en, config.xxxhdpi, dynamic_host, dynamic_host.config.en, dynamic_host.config.xxxhdpi]
com.flipkart.android: [chat, chat.config.xxxhdpi, config.arm64_v8a, config.xxxhdpi]
```

Some further docs digging showed that developers can add [Feature module manifests](https://developer.android.com/guide/app-bundle/dynamic-delivery#dynamic_feature_manifest) where gradle sets a split name for them.

Besides those custom names which are probably feature modules, there always seem to be at least one arch, display and lang split. It **would still be good to find some docs or code for those**, so we can be sure about what to expect here, so we can do our own compatibility checks.

For example:
* What characters are allowed in split names?
* What is their maximum length?
* Are feature suffixes like `config.xxxhdpi` standardized, so we can check for compatibility also when they appear on more than one name, e.g. `X.config.xxxhdpi`?

Unfortunately, everything seems to be inside proprietary Google libraries, especially inside [`SplitInstallManager`](https://developer.android.com/reference/com/google/android/play/core/splitinstall/SplitInstallManager).

**Comment by grote** [comment]
Some apps are at least showing a helpful error message instead of just crashing when installed without splits:

![device-2020-10-07-102449](https://user-images.githubusercontent.com/244947/95338284-289f4380-0889-11eb-92b6-cd59391c25d1.png)
