### ISSUE TITLE
Backup call-logs

### ISSUE THREAD

**Issue by grote** [stevesoltys/seedvault#93]
Currently, call logs are not part of the backup. However, with the `android.permission.READ_CALL_LOG`, we can back it up ourselves and with the corresponding WRITE permission restore it.

As mentioned in  #66, this app does this already and could be an inspiration: https://github.com/jberkel/sms-backup-plus

**Comment by grote** [comment]
For debugging things it can help to run:

    adb shell setprop log.tag.Dialer VERBOSE
    adb shell setprop log.tag.CallLogBackupAgent VERBOSE

The first one enables a call log simulator that can populate the database with dummy data. The second one gets your calllog backup debug output in logcat.

**Comment by chirayudesai** [comment]
Call logs are backed up now.
https://github.com/stevesoltys/seedvault/pull/113#issuecomment-691219295
