### ISSUE TITLE
Improve performance and reliability when using Nextcloud as storage location

### ISSUE THREAD

**Issue by grote** [stevesoltys/seedvault#95]
Optimize the interactions with Android's storage access framework (SAF) so that the number of network requests performed by Nextcloud is minimized to improve backup speed and reliability.

* [x] write (on-device) unit tests for the current storage abstraction [[PR](https://github.com/stevesoltys/seedvault/pull/107)]
* [x] replace usage of DocumentFile abstraction with fine-grained ContentProvider queries (was not beneficial, instead we eliminated parallelism as much as possible on our side) [[PR](https://github.com/stevesoltys/seedvault/pull/109)]
* [x] test and benchmark the effects against a Nextcloud test-instance
* [x] improve notification progress bar to account for extremely slow start when using Nextcloud [[PR](https://github.com/stevesoltys/seedvault/pull/111)]

**Comment by beerisgood** [comment]
If you need testing, I can help.

What I already can say is that using pin in Nextcloud app prevent sync but that may be Nextcloud (app) related.
