### ISSUE TITLE
Build inline in AOSP

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/seedvault#97]
To avoid having to use prebuilt APKs

**Comment by chirayudesai** [comment]
I tried to get this working when we were doing the initial work, but gave up after having lots of Kotlin issues.

@mikeNG has made a lot of progress on this recently.

Let's get this done to make it easier to include in other AOSP environments such as LineageOS

**Comment by chirayudesai** [comment]
`./gradlew androidDependencies` prints the deps, can be used for verification.

**Comment by mikeNG** [comment]
This can be closed now
